### ISSUE TITLE
CUDA_LAUNCH_BLOCKING=1

### ISSUE THREAD

**Issue by brookefzy** [OFA-Sys/OFA#145]
Hi I have been trying to finetune the ofa_large for the vqa project on a custom dataset. But I encountered the error below. Any insight or suggestions?
```
Traceback (most recent call last):
  File "/group/geog_pyloo/06_Timemachine/OFA/trainer.py", line 511, in load_checkpoint
    self.model.load_state_dict(
  File "/group/geog_pyloo/06_Timemachine/OFA/fairseq/fairseq/models/fairseq_model.py", line 125, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/yuanzf/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for OFAModel:
        While copying the parameter named "decoder.image_position_idx", whose dimensions in the model are torch.Size([1026]) and whose dimensions in the checkpoint are torch.Size([1026]), an exception occurred : ('CUDA error: invalid device function\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.',).
```

**Comment by logicwong** [comment]
@brookefzy Are you training in a distributed environment? If so, can you try training with single-GPU? You can refer to #102 and #130

**Comment by brookefzy** [comment]
I reinstalled fairseq and it works now. Thank you.
