### ISSUE TITLE
Multiple GPUs training error.

### ISSUE THREAD

**Issue by flymark2010** [OFA-Sys/OFA#286]
I want to train the pretraining task with multi-GPUs by modifying `run_scripts/pretraining/pretrain_ofa_base.sh`  as follows:
```
export CUDA_VISIBLE_DEVICES=3,4,5,6
export GPUS_PER_NODE=4
```

Run command `NCCL_DEBUG=INFO bash pretrain_ofa_base.sh`, and got error below:
```
distributed_utils.call_main(cfg, main)
  File "/workspace/project/OFA/fairseq/fairseq/distributed/utils.py", line 375, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/workspace/project/OFA/fairseq/fairseq/distributed/utils.py", line 343, in distributed_main
    cfg.distributed_training.distributed_rank = distributed_init(cfg)
  File "/workspace/project/OFA/fairseq/fairseq/distributed/utils.py", line 295, in distributed_init
    dist.all_reduce(torch.zeros(1).cuda())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
    work = default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, invalid usage, NCCL version 21.0.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
```

There are some debug info from NCLL:
```
cwclip-dev:53134:53400 [0] init.cc:521 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 8c000
cwclip-dev:53134:53400 [0] NCCL INFO init.cc:904 -> 5

cwclip-dev:53135:53401 [0] init.cc:521 NCCL WARN Duplicate GPU detected : rank 2 and rank 0 both on CUDA device 8c000
cwclip-dev:53135:53401 [0] NCCL INFO init.cc:904 -> 5
```

It seems that the model parameters and input tensors are not move to GPU according to the RANK. So, does this repo support multi-gpu training? Or do I need other configuration?

**Comment by JustinLin610** [comment]
I just tried 4 GPUs but did not meet any problem. Did you experiment on another device?

**Comment by flymark2010** [comment]
There is no problem with my devices. The problem is solved by adding `torch.cuda.set_device(cfg.distributed_training.distributed_rank)` in `distributed_init`.

**Comment by varunnrao** [comment]
I'm facing the same issue when I run `evaluate_caption.sh`. How do you fix this?

**Comment by Gusang-Lee** [comment]
@flymark2010 where did you in torch.cuda.set_device(cfg.distributed_training.distributed_rank) ?? which is in distributed_init. i want to know detailed location.
