### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by xidian2wuzhaoji** [OFA-Sys/OFA#65]
I wanted to run the given pretrain data examples, so I downloaded `pretrain_ data_ examples.zip` and unzip it into the directory `ofa/dataset/` , and rename it `pretrain_ data` (without `_examples`), I also downloaded `ofa_ base.pt` and put it in the directory `ofa/checkpoints/`.
when I cd the path into `ofa/run_scripts/pretraining/` and ran the command that `bash pretrain_ofa_base.sh`，I got the following error.  I searched on Google and got the suggestion to **check the type and value range of target involved in cross entropy calculation**, but I am not familar with this repo, anbody could  tell me how to sovle it?  I would appreciate it very much.
 
```
Traceback (most recent call last):
 File "../../train.py", line 528, in <module>
  cli_main()
 File "../../train.py", line 521, in cli_main
  distributed_utils.call_main(cfg, main)
 File "/media/wuzhaoji/Data/OFA/fairseq/distributed/utils.py", line 374, in call_main
  distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
 File "/media/wuzhaoji/Data/OFA/fairseq/distributed/utils.py", line 348, in distributed_main
  main(cfg, **kwargs)
 File "../../train.py", line 190, in main
  valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
 File "/home/wuzhaoji/anaconda3/envs/pytorch/lib/python3.7/contextlib.py", line 74, in inner
  return func(*args, **kwds)
 File "../../train.py", line 301, in train
  log_output = trainer.train_step(samples)
 File "/home/wuzhaoji/anaconda3/envs/pytorch/lib/python3.7/contextlib.py", line 74, in inner
  return func(*args, **kwds)
 File "/media/wuzhaoji/Data/OFA/trainer.py", line 806, in train_step
  raise e
 File "/media/wuzhaoji/Data/OFA/trainer.py", line 780, in train_step
  **extra_kwargs
 File "/media/wuzhaoji/Data/OFA/tasks/ofa_task.py", line 319, in train_step
  loss, sample_size, logging_output = criterion(model, sample, update_num=update_num)
 File "/home/wuzhaoji/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  return forward_call(*input, **kwargs)
 File "/media/wuzhaoji/Data/OFA/criterions/label_smoothed_cross_entropy.py", line 179, in forward
  loss_v1, sample_size_v1, logging_output_v1 = self.forward(model, sample[0], update_num, reduce)
 File "/media/wuzhaoji/Data/OFA/criterions/label_smoothed_cross_entropy.py" line 199, in forward
  net_output = model(**sample["net_input"])
 File "/home/wuzhaoji/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  return forward_call(*input, **kwargs)
 File "/media/wuzhaoji/Data/OFA/models/ofa/ofa.py", line 97, in forward
  sample_patch_num=sample_patch_num
 File "/home/wuzhaoji/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  return forward_call(*input, **kwargs)
 File "/media/wuzhaoji/Data/OFA/models/ofa/unify_transformer.py", line 670, in forward
  sample_patch_num)
 File "/media/wuzhaoji/Data/OFA/models/ofa/unify_transformer.py", line 737, in forward_scriptable
  if has_pads:
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. 
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
terminate called after throwing an instance of 'c10::CUDAError'
what(): CUDA error: device-side assert triggered....
```

**Comment by logicwong** [comment]
@xidian2wuzhaoji Hi, can you provide the complete error log? Also, is your PyTorch version 1.8.1?

**Comment by logicwong** [comment]
@xidian2wuzhaoji Hi, when I increased the batch_size, I reproduced the similar error, so I suspect your GPU memory is not enough to support `batch_size=4`, maybe reducing the batch_size can solve your problem.

**Comment by logicwong** [comment]
@xidian2wuzhaoji Thanks for your feedback, We found a bug in `unify_dataset.py`, the latest code has fixed this bug. Please check out the latest code and have a try.

**Comment by xidian2wuzhaoji** [comment]
hello, my pytorch version is 1.11.0

2022-04-09 12:25:57"Wang Peng" ***@***.***>写道：

@xidian2wuzhaoji Hi, can you provide the complete error log? Also, is your PyTorch version 1.8.1?

**Comment by xidian2wuzhaoji** [comment]
thank you very much, it has been sovled.

2022-04-11 16:31:59"Wang Peng" ***@***.***>写道：

@xidian2wuzhaoji Thanks for your feedback, We found a bug in unify_dataset.py, the latest code has fixed this bug. Please check out the latest code and have a try.
